/* File: _tricubmodule.c
 * This file is auto-generated with f2py (version:2).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * See http://cens.ioc.ee/projects/f2py2e/
 * Generation date: Mon Mar 14 13:03:23 2016
 * $Revision:$
 * $Date:$
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "Python.h"
#include <stdarg.h>
#include "fortranobject.h"
#include <math.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *_tricub_error;
static PyObject *_tricub_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
/*need_typedefs*/

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
#define rank(var) var ## _Rank
#define shape(var,dim) var ## _Dims[dim]
#define old_rank(var) (PyArray_NDIM((PyArrayObject *)(capi_ ## var ## _tmp)))
#define old_shape(var,dim) PyArray_DIM(((PyArrayObject *)(capi_ ## var ## _tmp)),dim)
#define fshape(var,dim) shape(var,rank(var)-dim-1)
#define len(var) shape(var,0)
#define flen(var) fshape(var,0)
#define old_size(var) PyArray_SIZE((PyArrayObject *)(capi_ ## var ## _tmp))
/* #define index(i) capi_i ## i */
#define slen(var) capi_ ## var ## _len
#define size(var, ...) f2py_size((PyArrayObject *)(capi_ ## var ## _tmp), ## __VA_ARGS__, -1)

#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
  PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
  fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif

#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif

#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif


/************************ See f2py2e/cfuncs.py: cfuncs ************************/
static int f2py_size(PyArrayObject* var, ...)
{
  npy_int sz = 0;
  npy_int dim;
  npy_int rank;
  va_list argp;
  va_start(argp, var);
  dim = va_arg(argp, npy_int);
  if (dim==-1)
    {
      sz = PyArray_SIZE(var);
    }
  else
    {
      rank = PyArray_NDIM(var);
      if (dim>=1 && dim<=rank)
        sz = PyArray_DIM(var, dim-1);
      else
        fprintf(stderr, "f2py_size: 2nd argument value=%d fails to satisfy 1<=value<=%d. Result will be 0.\n", dim, rank);
    }
  va_end(argp);
  return sz;
}

static int int_from_pyobj(int* v,PyObject *obj,const char *errmess) {
  PyObject* tmp = NULL;
  if (PyInt_Check(obj)) {
    *v = (int)PyInt_AS_LONG(obj);
    return 1;
  }
  tmp = PyNumber_Int(obj);
  if (tmp) {
    *v = PyInt_AS_LONG(tmp);
    Py_DECREF(tmp);
    return 1;
  }
  if (PyComplex_Check(obj))
    tmp = PyObject_GetAttrString(obj,"real");
  else if (PyString_Check(obj) || PyUnicode_Check(obj))
    /*pass*/;
  else if (PySequence_Check(obj))
    tmp = PySequence_GetItem(obj,0);
  if (tmp) {
    PyErr_Clear();
    if (int_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
    Py_DECREF(tmp);
  }
  {
    PyObject* err = PyErr_Occurred();
    if (err==NULL) err = _tricub_error;
    PyErr_SetString(err,errmess);
  }
  return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern void reg_eval(double*,double*,double*,double*,double*,int*,int*,int,int,int,int);
extern void reg_ev(double*,double*,double*,double*,double*,double*,double*,double*,int,int,int,int);
extern void nonreg_eval(double*,double*,double*,double*,double*,double*,double*,double*,int*,int*,int,int,int,int,int,int,int);
extern void nonreg_ev(double*,double*,double*,double*,double*,double*,double*,double*,int,int,int,int);
extern void ev(double*,double*,double*,double*,double*,double*,double*,double*,int,int,int,int);
extern int ismonotonic(double*,int);
extern int isregular(double*,int);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/********************************** reg_eval **********************************/
static char doc_f2py_rout__tricub_reg_eval[] = "\
val = reg_eval(dx0,dx1,dx2,f,pos,indx)\n\nWrapper for ``reg_eval``.\
\n\nParameters\n----------\n"
"dx0 : input rank-1 array('d') with bounds (ix)\n"
"dx1 : input rank-1 array('d') with bounds (ix)\n"
"dx2 : input rank-1 array('d') with bounds (ix)\n"
"f : input rank-3 array('d') with bounds (ix2,ix1,ix0)\n"
"pos : input rank-1 array('i') with bounds (ix)\n"
"indx : input rank-1 array('i') with bounds (ix)\n"
"\nReturns\n-------\n"
"val : rank-1 array('d') with bounds (ix)";
/* extern void reg_eval(double*,double*,double*,double*,double*,int*,int*,int,int,int,int); */
static PyObject *f2py_rout__tricub_reg_eval(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,double*,double*,double*,int*,int*,int,int,int,int)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double *val = NULL;
  npy_intp val_Dims[1] = {-1};
  const int val_Rank = 1;
  PyArrayObject *capi_val_tmp = NULL;
  int capi_val_intent = 0;
  double *dx0 = NULL;
  npy_intp dx0_Dims[1] = {-1};
  const int dx0_Rank = 1;
  PyArrayObject *capi_dx0_tmp = NULL;
  int capi_dx0_intent = 0;
  PyObject *dx0_capi = Py_None;
  double *dx1 = NULL;
  npy_intp dx1_Dims[1] = {-1};
  const int dx1_Rank = 1;
  PyArrayObject *capi_dx1_tmp = NULL;
  int capi_dx1_intent = 0;
  PyObject *dx1_capi = Py_None;
  double *dx2 = NULL;
  npy_intp dx2_Dims[1] = {-1};
  const int dx2_Rank = 1;
  PyArrayObject *capi_dx2_tmp = NULL;
  int capi_dx2_intent = 0;
  PyObject *dx2_capi = Py_None;
  double *f = NULL;
  npy_intp f_Dims[3] = {-1, -1, -1};
  const int f_Rank = 3;
  PyArrayObject *capi_f_tmp = NULL;
  int capi_f_intent = 0;
  PyObject *f_capi = Py_None;
  int *pos = NULL;
  npy_intp pos_Dims[1] = {-1};
  const int pos_Rank = 1;
  PyArrayObject *capi_pos_tmp = NULL;
  int capi_pos_intent = 0;
  PyObject *pos_capi = Py_None;
  int *indx = NULL;
  npy_intp indx_Dims[1] = {-1};
  const int indx_Rank = 1;
  PyArrayObject *capi_indx_tmp = NULL;
  int capi_indx_intent = 0;
  PyObject *indx_capi = Py_None;
  int ix0 = 0;
  int ix1 = 0;
  int ix2 = 0;
  int ix = 0;
  static char *capi_kwlist[] = {"dx0","dx1","dx2","f","pos","indx",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOO:_tricub.reg_eval",\
    capi_kwlist,&dx0_capi,&dx1_capi,&dx2_capi,&f_capi,&pos_capi,&indx_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable f */
  ;
  capi_f_intent |= F2PY_INTENT_C|F2PY_INTENT_IN;
  capi_f_tmp = array_from_pyobj(NPY_DOUBLE,f_Dims,f_Rank,capi_f_intent,f_capi);
  if (capi_f_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_tricub_error,"failed in converting 4th argument `f' of _tricub.reg_eval to C/Fortran array" );
  } else {
    f = (double *)(PyArray_DATA(capi_f_tmp));

  /* Processing variable dx0 */
  ;
  capi_dx0_intent |= F2PY_INTENT_C|F2PY_INTENT_IN;
  capi_dx0_tmp = array_from_pyobj(NPY_DOUBLE,dx0_Dims,dx0_Rank,capi_dx0_intent,dx0_capi);
  if (capi_dx0_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_tricub_error,"failed in converting 1st argument `dx0' of _tricub.reg_eval to C/Fortran array" );
  } else {
    dx0 = (double *)(PyArray_DATA(capi_dx0_tmp));

  /* Processing variable ix */
  ix = len(dx0);
  /* Processing variable val */
  val_Dims[0]=ix;
  capi_val_intent |= F2PY_INTENT_C|F2PY_INTENT_HIDE|F2PY_INTENT_OUT;
  capi_val_tmp = array_from_pyobj(NPY_DOUBLE,val_Dims,val_Rank,capi_val_intent,Py_None);
  if (capi_val_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_tricub_error,"failed in converting hidden `val' of _tricub.reg_eval to C/Fortran array" );
  } else {
    val = (double *)(PyArray_DATA(capi_val_tmp));

  /* Processing variable indx */
  indx_Dims[0]=ix;
  capi_indx_intent |= F2PY_INTENT_C|F2PY_INTENT_IN;
  capi_indx_tmp = array_from_pyobj(NPY_INT,indx_Dims,indx_Rank,capi_indx_intent,indx_capi);
  if (capi_indx_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_tricub_error,"failed in converting 6th argument `indx' of _tricub.reg_eval to C/Fortran array" );
  } else {
    indx = (int *)(PyArray_DATA(capi_indx_tmp));

  /* Processing variable dx1 */
  dx1_Dims[0]=ix;
  capi_dx1_intent |= F2PY_INTENT_C|F2PY_INTENT_IN;
  capi_dx1_tmp = array_from_pyobj(NPY_DOUBLE,dx1_Dims,dx1_Rank,capi_dx1_intent,dx1_capi);
  if (capi_dx1_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_tricub_error,"failed in converting 2nd argument `dx1' of _tricub.reg_eval to C/Fortran array" );
  } else {
    dx1 = (double *)(PyArray_DATA(capi_dx1_tmp));

  /* Processing variable dx2 */
  dx2_Dims[0]=ix;
  capi_dx2_intent |= F2PY_INTENT_C|F2PY_INTENT_IN;
  capi_dx2_tmp = array_from_pyobj(NPY_DOUBLE,dx2_Dims,dx2_Rank,capi_dx2_intent,dx2_capi);
  if (capi_dx2_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_tricub_error,"failed in converting 3rd argument `dx2' of _tricub.reg_eval to C/Fortran array" );
  } else {
    dx2 = (double *)(PyArray_DATA(capi_dx2_tmp));

  /* Processing variable pos */
  pos_Dims[0]=ix;
  capi_pos_intent |= F2PY_INTENT_C|F2PY_INTENT_IN;
  capi_pos_tmp = array_from_pyobj(NPY_INT,pos_Dims,pos_Rank,capi_pos_intent,pos_capi);
  if (capi_pos_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_tricub_error,"failed in converting 5th argument `pos' of _tricub.reg_eval to C/Fortran array" );
  } else {
    pos = (int *)(PyArray_DATA(capi_pos_tmp));

  /* Processing variable ix2 */
  ix2 = shape(f,0);
  /* Processing variable ix0 */
  ix0 = shape(f,2);
  /* Processing variable ix1 */
  ix1 = shape(f,1);
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(val,dx0,dx1,dx2,f,pos,indx,ix0,ix1,ix2,ix);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("N",capi_val_tmp);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  /* End of cleaning variable ix1 */
  /* End of cleaning variable ix0 */
  /* End of cleaning variable ix2 */
  if((PyObject *)capi_pos_tmp!=pos_capi) {
    Py_XDECREF(capi_pos_tmp); }
  }  /*if (capi_pos_tmp == NULL) ... else of pos*/
  /* End of cleaning variable pos */
  if((PyObject *)capi_dx2_tmp!=dx2_capi) {
    Py_XDECREF(capi_dx2_tmp); }
  }  /*if (capi_dx2_tmp == NULL) ... else of dx2*/
  /* End of cleaning variable dx2 */
  if((PyObject *)capi_dx1_tmp!=dx1_capi) {
    Py_XDECREF(capi_dx1_tmp); }
  }  /*if (capi_dx1_tmp == NULL) ... else of dx1*/
  /* End of cleaning variable dx1 */
  if((PyObject *)capi_indx_tmp!=indx_capi) {
    Py_XDECREF(capi_indx_tmp); }
  }  /*if (capi_indx_tmp == NULL) ... else of indx*/
  /* End of cleaning variable indx */
  }  /*if (capi_val_tmp == NULL) ... else of val*/
  /* End of cleaning variable val */
  /* End of cleaning variable ix */
  if((PyObject *)capi_dx0_tmp!=dx0_capi) {
    Py_XDECREF(capi_dx0_tmp); }
  }  /*if (capi_dx0_tmp == NULL) ... else of dx0*/
  /* End of cleaning variable dx0 */
  if((PyObject *)capi_f_tmp!=f_capi) {
    Py_XDECREF(capi_f_tmp); }
  }  /*if (capi_f_tmp == NULL) ... else of f*/
  /* End of cleaning variable f */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/****************************** end of reg_eval ******************************/

/*********************************** reg_ev ***********************************/
static char doc_f2py_rout__tricub_reg_ev[] = "\
val = reg_ev(x0,x1,x2,f,fx0,fx1,fx2)\n\nWrapper for ``reg_ev``.\
\n\nParameters\n----------\n"
"x0 : input rank-1 array('d') with bounds (ix)\n"
"x1 : input rank-1 array('d') with bounds (ix)\n"
"x2 : input rank-1 array('d') with bounds (ix)\n"
"f : input rank-3 array('d') with bounds (ix2,ix1,ix0)\n"
"fx0 : input rank-1 array('d') with bounds (ix0)\n"
"fx1 : input rank-1 array('d') with bounds (ix1)\n"
"fx2 : input rank-1 array('d') with bounds (ix2)\n"
"\nReturns\n-------\n"
"val : rank-1 array('d') with bounds (ix)";
/* extern void reg_ev(double*,double*,double*,double*,double*,double*,double*,double*,int,int,int,int); */
static PyObject *f2py_rout__tricub_reg_ev(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,double*,double*,double*,double*,double*,double*,int,int,int,int)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double *val = NULL;
  npy_intp val_Dims[1] = {-1};
  const int val_Rank = 1;
  PyArrayObject *capi_val_tmp = NULL;
  int capi_val_intent = 0;
  double *x0 = NULL;
  npy_intp x0_Dims[1] = {-1};
  const int x0_Rank = 1;
  PyArrayObject *capi_x0_tmp = NULL;
  int capi_x0_intent = 0;
  PyObject *x0_capi = Py_None;
  double *x1 = NULL;
  npy_intp x1_Dims[1] = {-1};
  const int x1_Rank = 1;
  PyArrayObject *capi_x1_tmp = NULL;
  int capi_x1_intent = 0;
  PyObject *x1_capi = Py_None;
  double *x2 = NULL;
  npy_intp x2_Dims[1] = {-1};
  const int x2_Rank = 1;
  PyArrayObject *capi_x2_tmp = NULL;
  int capi_x2_intent = 0;
  PyObject *x2_capi = Py_None;
  double *f = NULL;
  npy_intp f_Dims[3] = {-1, -1, -1};
  const int f_Rank = 3;
  PyArrayObject *capi_f_tmp = NULL;
  int capi_f_intent = 0;
  PyObject *f_capi = Py_None;
  double *fx0 = NULL;
  npy_intp fx0_Dims[1] = {-1};
  const int fx0_Rank = 1;
  PyArrayObject *capi_fx0_tmp = NULL;
  int capi_fx0_intent = 0;
  PyObject *fx0_capi = Py_None;
  double *fx1 = NULL;
  npy_intp fx1_Dims[1] = {-1};
  const int fx1_Rank = 1;
  PyArrayObject *capi_fx1_tmp = NULL;
  int capi_fx1_intent = 0;
  PyObject *fx1_capi = Py_None;
  double *fx2 = NULL;
  npy_intp fx2_Dims[1] = {-1};
  const int fx2_Rank = 1;
  PyArrayObject *capi_fx2_tmp = NULL;
  int capi_fx2_intent = 0;
  PyObject *fx2_capi = Py_None;
  int ix0 = 0;
  int ix1 = 0;
  int ix2 = 0;
  int ix = 0;
  static char *capi_kwlist[] = {"x0","x1","x2","f","fx0","fx1","fx2",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOO:_tricub.reg_ev",\
    capi_kwlist,&x0_capi,&x1_capi,&x2_capi,&f_capi,&fx0_capi,&fx1_capi,&fx2_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable f */
  ;
  capi_f_intent |= F2PY_INTENT_C|F2PY_INTENT_IN;
  capi_f_tmp = array_from_pyobj(NPY_DOUBLE,f_Dims,f_Rank,capi_f_intent,f_capi);
  if (capi_f_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_tricub_error,"failed in converting 4th argument `f' of _tricub.reg_ev to C/Fortran array" );
  } else {
    f = (double *)(PyArray_DATA(capi_f_tmp));

  /* Processing variable x0 */
  ;
  capi_x0_intent |= F2PY_INTENT_C|F2PY_INTENT_IN;
  capi_x0_tmp = array_from_pyobj(NPY_DOUBLE,x0_Dims,x0_Rank,capi_x0_intent,x0_capi);
  if (capi_x0_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_tricub_error,"failed in converting 1st argument `x0' of _tricub.reg_ev to C/Fortran array" );
  } else {
    x0 = (double *)(PyArray_DATA(capi_x0_tmp));

  /* Processing variable ix */
  ix = len(x0);
  /* Processing variable x1 */
  x1_Dims[0]=ix;
  capi_x1_intent |= F2PY_INTENT_C|F2PY_INTENT_IN;
  capi_x1_tmp = array_from_pyobj(NPY_DOUBLE,x1_Dims,x1_Rank,capi_x1_intent,x1_capi);
  if (capi_x1_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_tricub_error,"failed in converting 2nd argument `x1' of _tricub.reg_ev to C/Fortran array" );
  } else {
    x1 = (double *)(PyArray_DATA(capi_x1_tmp));

  /* Processing variable val */
  val_Dims[0]=ix;
  capi_val_intent |= F2PY_INTENT_C|F2PY_INTENT_HIDE|F2PY_INTENT_OUT;
  capi_val_tmp = array_from_pyobj(NPY_DOUBLE,val_Dims,val_Rank,capi_val_intent,Py_None);
  if (capi_val_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_tricub_error,"failed in converting hidden `val' of _tricub.reg_ev to C/Fortran array" );
  } else {
    val = (double *)(PyArray_DATA(capi_val_tmp));

  /* Processing variable x2 */
  x2_Dims[0]=ix;
  capi_x2_intent |= F2PY_INTENT_C|F2PY_INTENT_IN;
  capi_x2_tmp = array_from_pyobj(NPY_DOUBLE,x2_Dims,x2_Rank,capi_x2_intent,x2_capi);
  if (capi_x2_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_tricub_error,"failed in converting 3rd argument `x2' of _tricub.reg_ev to C/Fortran array" );
  } else {
    x2 = (double *)(PyArray_DATA(capi_x2_tmp));

  /* Processing variable ix2 */
  ix2 = shape(f,0);
  /* Processing variable ix1 */
  ix1 = shape(f,1);
  /* Processing variable ix0 */
  ix0 = shape(f,2);
  /* Processing variable fx1 */
  fx1_Dims[0]=ix1;
  capi_fx1_intent |= F2PY_INTENT_C|F2PY_INTENT_IN;
  capi_fx1_tmp = array_from_pyobj(NPY_DOUBLE,fx1_Dims,fx1_Rank,capi_fx1_intent,fx1_capi);
  if (capi_fx1_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_tricub_error,"failed in converting 6th argument `fx1' of _tricub.reg_ev to C/Fortran array" );
  } else {
    fx1 = (double *)(PyArray_DATA(capi_fx1_tmp));

  /* Processing variable fx0 */
  fx0_Dims[0]=ix0;
  capi_fx0_intent |= F2PY_INTENT_C|F2PY_INTENT_IN;
  capi_fx0_tmp = array_from_pyobj(NPY_DOUBLE,fx0_Dims,fx0_Rank,capi_fx0_intent,fx0_capi);
  if (capi_fx0_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_tricub_error,"failed in converting 5th argument `fx0' of _tricub.reg_ev to C/Fortran array" );
  } else {
    fx0 = (double *)(PyArray_DATA(capi_fx0_tmp));

  /* Processing variable fx2 */
  fx2_Dims[0]=ix2;
  capi_fx2_intent |= F2PY_INTENT_C|F2PY_INTENT_IN;
  capi_fx2_tmp = array_from_pyobj(NPY_DOUBLE,fx2_Dims,fx2_Rank,capi_fx2_intent,fx2_capi);
  if (capi_fx2_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_tricub_error,"failed in converting 7th argument `fx2' of _tricub.reg_ev to C/Fortran array" );
  } else {
    fx2 = (double *)(PyArray_DATA(capi_fx2_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(val,x0,x1,x2,f,fx0,fx1,fx2,ix0,ix1,ix2,ix);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("N",capi_val_tmp);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_fx2_tmp!=fx2_capi) {
    Py_XDECREF(capi_fx2_tmp); }
  }  /*if (capi_fx2_tmp == NULL) ... else of fx2*/
  /* End of cleaning variable fx2 */
  if((PyObject *)capi_fx0_tmp!=fx0_capi) {
    Py_XDECREF(capi_fx0_tmp); }
  }  /*if (capi_fx0_tmp == NULL) ... else of fx0*/
  /* End of cleaning variable fx0 */
  if((PyObject *)capi_fx1_tmp!=fx1_capi) {
    Py_XDECREF(capi_fx1_tmp); }
  }  /*if (capi_fx1_tmp == NULL) ... else of fx1*/
  /* End of cleaning variable fx1 */
  /* End of cleaning variable ix0 */
  /* End of cleaning variable ix1 */
  /* End of cleaning variable ix2 */
  if((PyObject *)capi_x2_tmp!=x2_capi) {
    Py_XDECREF(capi_x2_tmp); }
  }  /*if (capi_x2_tmp == NULL) ... else of x2*/
  /* End of cleaning variable x2 */
  }  /*if (capi_val_tmp == NULL) ... else of val*/
  /* End of cleaning variable val */
  if((PyObject *)capi_x1_tmp!=x1_capi) {
    Py_XDECREF(capi_x1_tmp); }
  }  /*if (capi_x1_tmp == NULL) ... else of x1*/
  /* End of cleaning variable x1 */
  /* End of cleaning variable ix */
  if((PyObject *)capi_x0_tmp!=x0_capi) {
    Py_XDECREF(capi_x0_tmp); }
  }  /*if (capi_x0_tmp == NULL) ... else of x0*/
  /* End of cleaning variable x0 */
  if((PyObject *)capi_f_tmp!=f_capi) {
    Py_XDECREF(capi_f_tmp); }
  }  /*if (capi_f_tmp == NULL) ... else of f*/
  /* End of cleaning variable f */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************* end of reg_ev *******************************/

/******************************** nonreg_eval ********************************/
static char doc_f2py_rout__tricub_nonreg_eval[] = "\
val = nonreg_eval(x0,x1,x2,f,fx0,fx1,fx2,pos,indx,in0,in1,in2)\n\nWrapper for ``nonreg_eval``.\
\n\nParameters\n----------\n"
"x0 : input rank-1 array('d') with bounds (ix)\n"
"x1 : input rank-1 array('d') with bounds (ix)\n"
"x2 : input rank-1 array('d') with bounds (ix)\n"
"f : input rank-3 array('d') with bounds (ix2,ix1,ix0)\n"
"fx0 : input rank-1 array('d') with bounds (ix0)\n"
"fx1 : input rank-1 array('d') with bounds (ix1)\n"
"fx2 : input rank-1 array('d') with bounds (ix2)\n"
"pos : input rank-1 array('i') with bounds (ix)\n"
"indx : input rank-1 array('i') with bounds (ix)\n"
"in0 : input int\n"
"in1 : input int\n"
"in2 : input int\n"
"\nReturns\n-------\n"
"val : rank-1 array('d') with bounds (ix)";
/* extern void nonreg_eval(double*,double*,double*,double*,double*,double*,double*,double*,int*,int*,int,int,int,int,int,int,int); */
static PyObject *f2py_rout__tricub_nonreg_eval(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,double*,double*,double*,double*,double*,double*,int*,int*,int,int,int,int,int,int,int)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double *val = NULL;
  npy_intp val_Dims[1] = {-1};
  const int val_Rank = 1;
  PyArrayObject *capi_val_tmp = NULL;
  int capi_val_intent = 0;
  double *x0 = NULL;
  npy_intp x0_Dims[1] = {-1};
  const int x0_Rank = 1;
  PyArrayObject *capi_x0_tmp = NULL;
  int capi_x0_intent = 0;
  PyObject *x0_capi = Py_None;
  double *x1 = NULL;
  npy_intp x1_Dims[1] = {-1};
  const int x1_Rank = 1;
  PyArrayObject *capi_x1_tmp = NULL;
  int capi_x1_intent = 0;
  PyObject *x1_capi = Py_None;
  double *x2 = NULL;
  npy_intp x2_Dims[1] = {-1};
  const int x2_Rank = 1;
  PyArrayObject *capi_x2_tmp = NULL;
  int capi_x2_intent = 0;
  PyObject *x2_capi = Py_None;
  double *f = NULL;
  npy_intp f_Dims[3] = {-1, -1, -1};
  const int f_Rank = 3;
  PyArrayObject *capi_f_tmp = NULL;
  int capi_f_intent = 0;
  PyObject *f_capi = Py_None;
  double *fx0 = NULL;
  npy_intp fx0_Dims[1] = {-1};
  const int fx0_Rank = 1;
  PyArrayObject *capi_fx0_tmp = NULL;
  int capi_fx0_intent = 0;
  PyObject *fx0_capi = Py_None;
  double *fx1 = NULL;
  npy_intp fx1_Dims[1] = {-1};
  const int fx1_Rank = 1;
  PyArrayObject *capi_fx1_tmp = NULL;
  int capi_fx1_intent = 0;
  PyObject *fx1_capi = Py_None;
  double *fx2 = NULL;
  npy_intp fx2_Dims[1] = {-1};
  const int fx2_Rank = 1;
  PyArrayObject *capi_fx2_tmp = NULL;
  int capi_fx2_intent = 0;
  PyObject *fx2_capi = Py_None;
  int *pos = NULL;
  npy_intp pos_Dims[1] = {-1};
  const int pos_Rank = 1;
  PyArrayObject *capi_pos_tmp = NULL;
  int capi_pos_intent = 0;
  PyObject *pos_capi = Py_None;
  int *indx = NULL;
  npy_intp indx_Dims[1] = {-1};
  const int indx_Rank = 1;
  PyArrayObject *capi_indx_tmp = NULL;
  int capi_indx_intent = 0;
  PyObject *indx_capi = Py_None;
  int in0 = 0;
  PyObject *in0_capi = Py_None;
  int in1 = 0;
  PyObject *in1_capi = Py_None;
  int in2 = 0;
  PyObject *in2_capi = Py_None;
  int ix0 = 0;
  int ix1 = 0;
  int ix2 = 0;
  int ix = 0;
  static char *capi_kwlist[] = {"x0","x1","x2","f","fx0","fx1","fx2","pos","indx","in0","in1","in2",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOOOOOOO:_tricub.nonreg_eval",\
    capi_kwlist,&x0_capi,&x1_capi,&x2_capi,&f_capi,&fx0_capi,&fx1_capi,&fx2_capi,&pos_capi,&indx_capi,&in0_capi,&in1_capi,&in2_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable in0 */
    f2py_success = int_from_pyobj(&in0,in0_capi,"_tricub.nonreg_eval() 10th argument (in0) can't be converted to int");
  if (f2py_success) {
  /* Processing variable in1 */
    f2py_success = int_from_pyobj(&in1,in1_capi,"_tricub.nonreg_eval() 11st argument (in1) can't be converted to int");
  if (f2py_success) {
  /* Processing variable in2 */
    f2py_success = int_from_pyobj(&in2,in2_capi,"_tricub.nonreg_eval() 12nd argument (in2) can't be converted to int");
  if (f2py_success) {
  /* Processing variable f */
  ;
  capi_f_intent |= F2PY_INTENT_C|F2PY_INTENT_IN;
  capi_f_tmp = array_from_pyobj(NPY_DOUBLE,f_Dims,f_Rank,capi_f_intent,f_capi);
  if (capi_f_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_tricub_error,"failed in converting 4th argument `f' of _tricub.nonreg_eval to C/Fortran array" );
  } else {
    f = (double *)(PyArray_DATA(capi_f_tmp));

  /* Processing variable ix */
  ix = len(x0);
  /* Processing variable x2 */
  x2_Dims[0]=ix;
  capi_x2_intent |= F2PY_INTENT_C|F2PY_INTENT_IN;
  capi_x2_tmp = array_from_pyobj(NPY_DOUBLE,x2_Dims,x2_Rank,capi_x2_intent,x2_capi);
  if (capi_x2_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_tricub_error,"failed in converting 3rd argument `x2' of _tricub.nonreg_eval to C/Fortran array" );
  } else {
    x2 = (double *)(PyArray_DATA(capi_x2_tmp));

  /* Processing variable x0 */
  x0_Dims[0]=ix;
  capi_x0_intent |= F2PY_INTENT_C|F2PY_INTENT_IN;
  capi_x0_tmp = array_from_pyobj(NPY_DOUBLE,x0_Dims,x0_Rank,capi_x0_intent,x0_capi);
  if (capi_x0_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_tricub_error,"failed in converting 1st argument `x0' of _tricub.nonreg_eval to C/Fortran array" );
  } else {
    x0 = (double *)(PyArray_DATA(capi_x0_tmp));

  /* Processing variable x1 */
  x1_Dims[0]=ix;
  capi_x1_intent |= F2PY_INTENT_C|F2PY_INTENT_IN;
  capi_x1_tmp = array_from_pyobj(NPY_DOUBLE,x1_Dims,x1_Rank,capi_x1_intent,x1_capi);
  if (capi_x1_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_tricub_error,"failed in converting 2nd argument `x1' of _tricub.nonreg_eval to C/Fortran array" );
  } else {
    x1 = (double *)(PyArray_DATA(capi_x1_tmp));

  /* Processing variable val */
  val_Dims[0]=ix;
  capi_val_intent |= F2PY_INTENT_C|F2PY_INTENT_HIDE|F2PY_INTENT_OUT;
  capi_val_tmp = array_from_pyobj(NPY_DOUBLE,val_Dims,val_Rank,capi_val_intent,Py_None);
  if (capi_val_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_tricub_error,"failed in converting hidden `val' of _tricub.nonreg_eval to C/Fortran array" );
  } else {
    val = (double *)(PyArray_DATA(capi_val_tmp));

  /* Processing variable indx */
  indx_Dims[0]=ix;
  capi_indx_intent |= F2PY_INTENT_C|F2PY_INTENT_IN;
  capi_indx_tmp = array_from_pyobj(NPY_INT,indx_Dims,indx_Rank,capi_indx_intent,indx_capi);
  if (capi_indx_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_tricub_error,"failed in converting 9th argument `indx' of _tricub.nonreg_eval to C/Fortran array" );
  } else {
    indx = (int *)(PyArray_DATA(capi_indx_tmp));

  /* Processing variable pos */
  pos_Dims[0]=ix;
  capi_pos_intent |= F2PY_INTENT_C|F2PY_INTENT_IN;
  capi_pos_tmp = array_from_pyobj(NPY_INT,pos_Dims,pos_Rank,capi_pos_intent,pos_capi);
  if (capi_pos_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_tricub_error,"failed in converting 8th argument `pos' of _tricub.nonreg_eval to C/Fortran array" );
  } else {
    pos = (int *)(PyArray_DATA(capi_pos_tmp));

  /* Processing variable ix2 */
  ix2 = shape(f,0);
  /* Processing variable ix0 */
  ix0 = shape(f,2);
  /* Processing variable ix1 */
  ix1 = shape(f,1);
  /* Processing variable fx0 */
  fx0_Dims[0]=ix0;
  capi_fx0_intent |= F2PY_INTENT_C|F2PY_INTENT_IN;
  capi_fx0_tmp = array_from_pyobj(NPY_DOUBLE,fx0_Dims,fx0_Rank,capi_fx0_intent,fx0_capi);
  if (capi_fx0_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_tricub_error,"failed in converting 5th argument `fx0' of _tricub.nonreg_eval to C/Fortran array" );
  } else {
    fx0 = (double *)(PyArray_DATA(capi_fx0_tmp));

  /* Processing variable fx1 */
  fx1_Dims[0]=ix1;
  capi_fx1_intent |= F2PY_INTENT_C|F2PY_INTENT_IN;
  capi_fx1_tmp = array_from_pyobj(NPY_DOUBLE,fx1_Dims,fx1_Rank,capi_fx1_intent,fx1_capi);
  if (capi_fx1_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_tricub_error,"failed in converting 6th argument `fx1' of _tricub.nonreg_eval to C/Fortran array" );
  } else {
    fx1 = (double *)(PyArray_DATA(capi_fx1_tmp));

  /* Processing variable fx2 */
  fx2_Dims[0]=ix2;
  capi_fx2_intent |= F2PY_INTENT_C|F2PY_INTENT_IN;
  capi_fx2_tmp = array_from_pyobj(NPY_DOUBLE,fx2_Dims,fx2_Rank,capi_fx2_intent,fx2_capi);
  if (capi_fx2_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_tricub_error,"failed in converting 7th argument `fx2' of _tricub.nonreg_eval to C/Fortran array" );
  } else {
    fx2 = (double *)(PyArray_DATA(capi_fx2_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(val,x0,x1,x2,f,fx0,fx1,fx2,pos,indx,in0,in1,in2,ix0,ix1,ix2,ix);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("N",capi_val_tmp);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_fx2_tmp!=fx2_capi) {
    Py_XDECREF(capi_fx2_tmp); }
  }  /*if (capi_fx2_tmp == NULL) ... else of fx2*/
  /* End of cleaning variable fx2 */
  if((PyObject *)capi_fx1_tmp!=fx1_capi) {
    Py_XDECREF(capi_fx1_tmp); }
  }  /*if (capi_fx1_tmp == NULL) ... else of fx1*/
  /* End of cleaning variable fx1 */
  if((PyObject *)capi_fx0_tmp!=fx0_capi) {
    Py_XDECREF(capi_fx0_tmp); }
  }  /*if (capi_fx0_tmp == NULL) ... else of fx0*/
  /* End of cleaning variable fx0 */
  /* End of cleaning variable ix1 */
  /* End of cleaning variable ix0 */
  /* End of cleaning variable ix2 */
  if((PyObject *)capi_pos_tmp!=pos_capi) {
    Py_XDECREF(capi_pos_tmp); }
  }  /*if (capi_pos_tmp == NULL) ... else of pos*/
  /* End of cleaning variable pos */
  if((PyObject *)capi_indx_tmp!=indx_capi) {
    Py_XDECREF(capi_indx_tmp); }
  }  /*if (capi_indx_tmp == NULL) ... else of indx*/
  /* End of cleaning variable indx */
  }  /*if (capi_val_tmp == NULL) ... else of val*/
  /* End of cleaning variable val */
  if((PyObject *)capi_x1_tmp!=x1_capi) {
    Py_XDECREF(capi_x1_tmp); }
  }  /*if (capi_x1_tmp == NULL) ... else of x1*/
  /* End of cleaning variable x1 */
  if((PyObject *)capi_x0_tmp!=x0_capi) {
    Py_XDECREF(capi_x0_tmp); }
  }  /*if (capi_x0_tmp == NULL) ... else of x0*/
  /* End of cleaning variable x0 */
  if((PyObject *)capi_x2_tmp!=x2_capi) {
    Py_XDECREF(capi_x2_tmp); }
  }  /*if (capi_x2_tmp == NULL) ... else of x2*/
  /* End of cleaning variable x2 */
  /* End of cleaning variable ix */
  if((PyObject *)capi_f_tmp!=f_capi) {
    Py_XDECREF(capi_f_tmp); }
  }  /*if (capi_f_tmp == NULL) ... else of f*/
  /* End of cleaning variable f */
  } /*if (f2py_success) of in2*/
  /* End of cleaning variable in2 */
  } /*if (f2py_success) of in1*/
  /* End of cleaning variable in1 */
  } /*if (f2py_success) of in0*/
  /* End of cleaning variable in0 */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/***************************** end of nonreg_eval *****************************/

/********************************* nonreg_ev *********************************/
static char doc_f2py_rout__tricub_nonreg_ev[] = "\
val = nonreg_ev(x0,x1,x2,f,fx0,fx1,fx2)\n\nWrapper for ``nonreg_ev``.\
\n\nParameters\n----------\n"
"x0 : input rank-1 array('d') with bounds (ix)\n"
"x1 : input rank-1 array('d') with bounds (ix)\n"
"x2 : input rank-1 array('d') with bounds (ix)\n"
"f : input rank-3 array('d') with bounds (ix2,ix1,ix0)\n"
"fx0 : input rank-1 array('d') with bounds (ix0)\n"
"fx1 : input rank-1 array('d') with bounds (ix1)\n"
"fx2 : input rank-1 array('d') with bounds (ix2)\n"
"\nReturns\n-------\n"
"val : rank-1 array('d') with bounds (ix)";
/* extern void nonreg_ev(double*,double*,double*,double*,double*,double*,double*,double*,int,int,int,int); */
static PyObject *f2py_rout__tricub_nonreg_ev(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,double*,double*,double*,double*,double*,double*,int,int,int,int)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double *val = NULL;
  npy_intp val_Dims[1] = {-1};
  const int val_Rank = 1;
  PyArrayObject *capi_val_tmp = NULL;
  int capi_val_intent = 0;
  double *x0 = NULL;
  npy_intp x0_Dims[1] = {-1};
  const int x0_Rank = 1;
  PyArrayObject *capi_x0_tmp = NULL;
  int capi_x0_intent = 0;
  PyObject *x0_capi = Py_None;
  double *x1 = NULL;
  npy_intp x1_Dims[1] = {-1};
  const int x1_Rank = 1;
  PyArrayObject *capi_x1_tmp = NULL;
  int capi_x1_intent = 0;
  PyObject *x1_capi = Py_None;
  double *x2 = NULL;
  npy_intp x2_Dims[1] = {-1};
  const int x2_Rank = 1;
  PyArrayObject *capi_x2_tmp = NULL;
  int capi_x2_intent = 0;
  PyObject *x2_capi = Py_None;
  double *f = NULL;
  npy_intp f_Dims[3] = {-1, -1, -1};
  const int f_Rank = 3;
  PyArrayObject *capi_f_tmp = NULL;
  int capi_f_intent = 0;
  PyObject *f_capi = Py_None;
  double *fx0 = NULL;
  npy_intp fx0_Dims[1] = {-1};
  const int fx0_Rank = 1;
  PyArrayObject *capi_fx0_tmp = NULL;
  int capi_fx0_intent = 0;
  PyObject *fx0_capi = Py_None;
  double *fx1 = NULL;
  npy_intp fx1_Dims[1] = {-1};
  const int fx1_Rank = 1;
  PyArrayObject *capi_fx1_tmp = NULL;
  int capi_fx1_intent = 0;
  PyObject *fx1_capi = Py_None;
  double *fx2 = NULL;
  npy_intp fx2_Dims[1] = {-1};
  const int fx2_Rank = 1;
  PyArrayObject *capi_fx2_tmp = NULL;
  int capi_fx2_intent = 0;
  PyObject *fx2_capi = Py_None;
  int ix0 = 0;
  int ix1 = 0;
  int ix2 = 0;
  int ix = 0;
  static char *capi_kwlist[] = {"x0","x1","x2","f","fx0","fx1","fx2",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOO:_tricub.nonreg_ev",\
    capi_kwlist,&x0_capi,&x1_capi,&x2_capi,&f_capi,&fx0_capi,&fx1_capi,&fx2_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable f */
  ;
  capi_f_intent |= F2PY_INTENT_C|F2PY_INTENT_IN;
  capi_f_tmp = array_from_pyobj(NPY_DOUBLE,f_Dims,f_Rank,capi_f_intent,f_capi);
  if (capi_f_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_tricub_error,"failed in converting 4th argument `f' of _tricub.nonreg_ev to C/Fortran array" );
  } else {
    f = (double *)(PyArray_DATA(capi_f_tmp));

  /* Processing variable x0 */
  ;
  capi_x0_intent |= F2PY_INTENT_C|F2PY_INTENT_IN;
  capi_x0_tmp = array_from_pyobj(NPY_DOUBLE,x0_Dims,x0_Rank,capi_x0_intent,x0_capi);
  if (capi_x0_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_tricub_error,"failed in converting 1st argument `x0' of _tricub.nonreg_ev to C/Fortran array" );
  } else {
    x0 = (double *)(PyArray_DATA(capi_x0_tmp));

  /* Processing variable ix */
  ix = len(x0);
  /* Processing variable x1 */
  x1_Dims[0]=ix;
  capi_x1_intent |= F2PY_INTENT_C|F2PY_INTENT_IN;
  capi_x1_tmp = array_from_pyobj(NPY_DOUBLE,x1_Dims,x1_Rank,capi_x1_intent,x1_capi);
  if (capi_x1_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_tricub_error,"failed in converting 2nd argument `x1' of _tricub.nonreg_ev to C/Fortran array" );
  } else {
    x1 = (double *)(PyArray_DATA(capi_x1_tmp));

  /* Processing variable val */
  val_Dims[0]=ix;
  capi_val_intent |= F2PY_INTENT_C|F2PY_INTENT_HIDE|F2PY_INTENT_OUT;
  capi_val_tmp = array_from_pyobj(NPY_DOUBLE,val_Dims,val_Rank,capi_val_intent,Py_None);
  if (capi_val_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_tricub_error,"failed in converting hidden `val' of _tricub.nonreg_ev to C/Fortran array" );
  } else {
    val = (double *)(PyArray_DATA(capi_val_tmp));

  /* Processing variable x2 */
  x2_Dims[0]=ix;
  capi_x2_intent |= F2PY_INTENT_C|F2PY_INTENT_IN;
  capi_x2_tmp = array_from_pyobj(NPY_DOUBLE,x2_Dims,x2_Rank,capi_x2_intent,x2_capi);
  if (capi_x2_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_tricub_error,"failed in converting 3rd argument `x2' of _tricub.nonreg_ev to C/Fortran array" );
  } else {
    x2 = (double *)(PyArray_DATA(capi_x2_tmp));

  /* Processing variable ix2 */
  ix2 = shape(f,0);
  /* Processing variable ix1 */
  ix1 = shape(f,1);
  /* Processing variable ix0 */
  ix0 = shape(f,2);
  /* Processing variable fx1 */
  fx1_Dims[0]=ix1;
  capi_fx1_intent |= F2PY_INTENT_C|F2PY_INTENT_IN;
  capi_fx1_tmp = array_from_pyobj(NPY_DOUBLE,fx1_Dims,fx1_Rank,capi_fx1_intent,fx1_capi);
  if (capi_fx1_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_tricub_error,"failed in converting 6th argument `fx1' of _tricub.nonreg_ev to C/Fortran array" );
  } else {
    fx1 = (double *)(PyArray_DATA(capi_fx1_tmp));

  /* Processing variable fx0 */
  fx0_Dims[0]=ix0;
  capi_fx0_intent |= F2PY_INTENT_C|F2PY_INTENT_IN;
  capi_fx0_tmp = array_from_pyobj(NPY_DOUBLE,fx0_Dims,fx0_Rank,capi_fx0_intent,fx0_capi);
  if (capi_fx0_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_tricub_error,"failed in converting 5th argument `fx0' of _tricub.nonreg_ev to C/Fortran array" );
  } else {
    fx0 = (double *)(PyArray_DATA(capi_fx0_tmp));

  /* Processing variable fx2 */
  fx2_Dims[0]=ix2;
  capi_fx2_intent |= F2PY_INTENT_C|F2PY_INTENT_IN;
  capi_fx2_tmp = array_from_pyobj(NPY_DOUBLE,fx2_Dims,fx2_Rank,capi_fx2_intent,fx2_capi);
  if (capi_fx2_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_tricub_error,"failed in converting 7th argument `fx2' of _tricub.nonreg_ev to C/Fortran array" );
  } else {
    fx2 = (double *)(PyArray_DATA(capi_fx2_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(val,x0,x1,x2,f,fx0,fx1,fx2,ix0,ix1,ix2,ix);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("N",capi_val_tmp);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_fx2_tmp!=fx2_capi) {
    Py_XDECREF(capi_fx2_tmp); }
  }  /*if (capi_fx2_tmp == NULL) ... else of fx2*/
  /* End of cleaning variable fx2 */
  if((PyObject *)capi_fx0_tmp!=fx0_capi) {
    Py_XDECREF(capi_fx0_tmp); }
  }  /*if (capi_fx0_tmp == NULL) ... else of fx0*/
  /* End of cleaning variable fx0 */
  if((PyObject *)capi_fx1_tmp!=fx1_capi) {
    Py_XDECREF(capi_fx1_tmp); }
  }  /*if (capi_fx1_tmp == NULL) ... else of fx1*/
  /* End of cleaning variable fx1 */
  /* End of cleaning variable ix0 */
  /* End of cleaning variable ix1 */
  /* End of cleaning variable ix2 */
  if((PyObject *)capi_x2_tmp!=x2_capi) {
    Py_XDECREF(capi_x2_tmp); }
  }  /*if (capi_x2_tmp == NULL) ... else of x2*/
  /* End of cleaning variable x2 */
  }  /*if (capi_val_tmp == NULL) ... else of val*/
  /* End of cleaning variable val */
  if((PyObject *)capi_x1_tmp!=x1_capi) {
    Py_XDECREF(capi_x1_tmp); }
  }  /*if (capi_x1_tmp == NULL) ... else of x1*/
  /* End of cleaning variable x1 */
  /* End of cleaning variable ix */
  if((PyObject *)capi_x0_tmp!=x0_capi) {
    Py_XDECREF(capi_x0_tmp); }
  }  /*if (capi_x0_tmp == NULL) ... else of x0*/
  /* End of cleaning variable x0 */
  if((PyObject *)capi_f_tmp!=f_capi) {
    Py_XDECREF(capi_f_tmp); }
  }  /*if (capi_f_tmp == NULL) ... else of f*/
  /* End of cleaning variable f */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/****************************** end of nonreg_ev ******************************/

/************************************* ev *************************************/
static char doc_f2py_rout__tricub_ev[] = "\
val = ev(x0,x1,x2,f,fx0,fx1,fx2)\n\nWrapper for ``ev``.\
\n\nParameters\n----------\n"
"x0 : input rank-1 array('d') with bounds (ix)\n"
"x1 : input rank-1 array('d') with bounds (ix)\n"
"x2 : input rank-1 array('d') with bounds (ix)\n"
"f : input rank-3 array('d') with bounds (ix2,ix1,ix0)\n"
"fx0 : input rank-1 array('d') with bounds (ix0)\n"
"fx1 : input rank-1 array('d') with bounds (ix1)\n"
"fx2 : input rank-1 array('d') with bounds (ix2)\n"
"\nReturns\n-------\n"
"val : rank-1 array('d') with bounds (ix)";
/* extern void ev(double*,double*,double*,double*,double*,double*,double*,double*,int,int,int,int); */
static PyObject *f2py_rout__tricub_ev(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,double*,double*,double*,double*,double*,double*,int,int,int,int)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double *val = NULL;
  npy_intp val_Dims[1] = {-1};
  const int val_Rank = 1;
  PyArrayObject *capi_val_tmp = NULL;
  int capi_val_intent = 0;
  double *x0 = NULL;
  npy_intp x0_Dims[1] = {-1};
  const int x0_Rank = 1;
  PyArrayObject *capi_x0_tmp = NULL;
  int capi_x0_intent = 0;
  PyObject *x0_capi = Py_None;
  double *x1 = NULL;
  npy_intp x1_Dims[1] = {-1};
  const int x1_Rank = 1;
  PyArrayObject *capi_x1_tmp = NULL;
  int capi_x1_intent = 0;
  PyObject *x1_capi = Py_None;
  double *x2 = NULL;
  npy_intp x2_Dims[1] = {-1};
  const int x2_Rank = 1;
  PyArrayObject *capi_x2_tmp = NULL;
  int capi_x2_intent = 0;
  PyObject *x2_capi = Py_None;
  double *f = NULL;
  npy_intp f_Dims[3] = {-1, -1, -1};
  const int f_Rank = 3;
  PyArrayObject *capi_f_tmp = NULL;
  int capi_f_intent = 0;
  PyObject *f_capi = Py_None;
  double *fx0 = NULL;
  npy_intp fx0_Dims[1] = {-1};
  const int fx0_Rank = 1;
  PyArrayObject *capi_fx0_tmp = NULL;
  int capi_fx0_intent = 0;
  PyObject *fx0_capi = Py_None;
  double *fx1 = NULL;
  npy_intp fx1_Dims[1] = {-1};
  const int fx1_Rank = 1;
  PyArrayObject *capi_fx1_tmp = NULL;
  int capi_fx1_intent = 0;
  PyObject *fx1_capi = Py_None;
  double *fx2 = NULL;
  npy_intp fx2_Dims[1] = {-1};
  const int fx2_Rank = 1;
  PyArrayObject *capi_fx2_tmp = NULL;
  int capi_fx2_intent = 0;
  PyObject *fx2_capi = Py_None;
  int ix0 = 0;
  int ix1 = 0;
  int ix2 = 0;
  int ix = 0;
  static char *capi_kwlist[] = {"x0","x1","x2","f","fx0","fx1","fx2",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOO:_tricub.ev",\
    capi_kwlist,&x0_capi,&x1_capi,&x2_capi,&f_capi,&fx0_capi,&fx1_capi,&fx2_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable f */
  ;
  capi_f_intent |= F2PY_INTENT_C|F2PY_INTENT_IN;
  capi_f_tmp = array_from_pyobj(NPY_DOUBLE,f_Dims,f_Rank,capi_f_intent,f_capi);
  if (capi_f_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_tricub_error,"failed in converting 4th argument `f' of _tricub.ev to C/Fortran array" );
  } else {
    f = (double *)(PyArray_DATA(capi_f_tmp));

  /* Processing variable x0 */
  ;
  capi_x0_intent |= F2PY_INTENT_C|F2PY_INTENT_IN;
  capi_x0_tmp = array_from_pyobj(NPY_DOUBLE,x0_Dims,x0_Rank,capi_x0_intent,x0_capi);
  if (capi_x0_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_tricub_error,"failed in converting 1st argument `x0' of _tricub.ev to C/Fortran array" );
  } else {
    x0 = (double *)(PyArray_DATA(capi_x0_tmp));

  /* Processing variable ix */
  ix = len(x0);
  /* Processing variable ix1 */
  ix1 = shape(f,1);
  /* Processing variable val */
  val_Dims[0]=ix;
  capi_val_intent |= F2PY_INTENT_C|F2PY_INTENT_HIDE|F2PY_INTENT_OUT;
  capi_val_tmp = array_from_pyobj(NPY_DOUBLE,val_Dims,val_Rank,capi_val_intent,Py_None);
  if (capi_val_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_tricub_error,"failed in converting hidden `val' of _tricub.ev to C/Fortran array" );
  } else {
    val = (double *)(PyArray_DATA(capi_val_tmp));

  /* Processing variable fx1 */
  fx1_Dims[0]=ix1;
  capi_fx1_intent |= F2PY_INTENT_C|F2PY_INTENT_IN;
  capi_fx1_tmp = array_from_pyobj(NPY_DOUBLE,fx1_Dims,fx1_Rank,capi_fx1_intent,fx1_capi);
  if (capi_fx1_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_tricub_error,"failed in converting 6th argument `fx1' of _tricub.ev to C/Fortran array" );
  } else {
    fx1 = (double *)(PyArray_DATA(capi_fx1_tmp));

  /* Processing variable x2 */
  x2_Dims[0]=ix;
  capi_x2_intent |= F2PY_INTENT_C|F2PY_INTENT_IN;
  capi_x2_tmp = array_from_pyobj(NPY_DOUBLE,x2_Dims,x2_Rank,capi_x2_intent,x2_capi);
  if (capi_x2_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_tricub_error,"failed in converting 3rd argument `x2' of _tricub.ev to C/Fortran array" );
  } else {
    x2 = (double *)(PyArray_DATA(capi_x2_tmp));

  /* Processing variable ix2 */
  ix2 = shape(f,0);
  /* Processing variable x1 */
  x1_Dims[0]=ix;
  capi_x1_intent |= F2PY_INTENT_C|F2PY_INTENT_IN;
  capi_x1_tmp = array_from_pyobj(NPY_DOUBLE,x1_Dims,x1_Rank,capi_x1_intent,x1_capi);
  if (capi_x1_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_tricub_error,"failed in converting 2nd argument `x1' of _tricub.ev to C/Fortran array" );
  } else {
    x1 = (double *)(PyArray_DATA(capi_x1_tmp));

  /* Processing variable ix0 */
  ix0 = shape(f,2);
  /* Processing variable fx0 */
  fx0_Dims[0]=ix0;
  capi_fx0_intent |= F2PY_INTENT_C|F2PY_INTENT_IN;
  capi_fx0_tmp = array_from_pyobj(NPY_DOUBLE,fx0_Dims,fx0_Rank,capi_fx0_intent,fx0_capi);
  if (capi_fx0_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_tricub_error,"failed in converting 5th argument `fx0' of _tricub.ev to C/Fortran array" );
  } else {
    fx0 = (double *)(PyArray_DATA(capi_fx0_tmp));

  /* Processing variable fx2 */
  fx2_Dims[0]=ix2;
  capi_fx2_intent |= F2PY_INTENT_C|F2PY_INTENT_IN;
  capi_fx2_tmp = array_from_pyobj(NPY_DOUBLE,fx2_Dims,fx2_Rank,capi_fx2_intent,fx2_capi);
  if (capi_fx2_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_tricub_error,"failed in converting 7th argument `fx2' of _tricub.ev to C/Fortran array" );
  } else {
    fx2 = (double *)(PyArray_DATA(capi_fx2_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(val,x0,x1,x2,f,fx0,fx1,fx2,ix0,ix1,ix2,ix);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("N",capi_val_tmp);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_fx2_tmp!=fx2_capi) {
    Py_XDECREF(capi_fx2_tmp); }
  }  /*if (capi_fx2_tmp == NULL) ... else of fx2*/
  /* End of cleaning variable fx2 */
  if((PyObject *)capi_fx0_tmp!=fx0_capi) {
    Py_XDECREF(capi_fx0_tmp); }
  }  /*if (capi_fx0_tmp == NULL) ... else of fx0*/
  /* End of cleaning variable fx0 */
  /* End of cleaning variable ix0 */
  if((PyObject *)capi_x1_tmp!=x1_capi) {
    Py_XDECREF(capi_x1_tmp); }
  }  /*if (capi_x1_tmp == NULL) ... else of x1*/
  /* End of cleaning variable x1 */
  /* End of cleaning variable ix2 */
  if((PyObject *)capi_x2_tmp!=x2_capi) {
    Py_XDECREF(capi_x2_tmp); }
  }  /*if (capi_x2_tmp == NULL) ... else of x2*/
  /* End of cleaning variable x2 */
  if((PyObject *)capi_fx1_tmp!=fx1_capi) {
    Py_XDECREF(capi_fx1_tmp); }
  }  /*if (capi_fx1_tmp == NULL) ... else of fx1*/
  /* End of cleaning variable fx1 */
  }  /*if (capi_val_tmp == NULL) ... else of val*/
  /* End of cleaning variable val */
  /* End of cleaning variable ix1 */
  /* End of cleaning variable ix */
  if((PyObject *)capi_x0_tmp!=x0_capi) {
    Py_XDECREF(capi_x0_tmp); }
  }  /*if (capi_x0_tmp == NULL) ... else of x0*/
  /* End of cleaning variable x0 */
  if((PyObject *)capi_f_tmp!=f_capi) {
    Py_XDECREF(capi_f_tmp); }
  }  /*if (capi_f_tmp == NULL) ... else of f*/
  /* End of cleaning variable f */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/********************************* end of ev *********************************/

/******************************** ismonotonic ********************************/
static char doc_f2py_rout__tricub_ismonotonic[] = "\
ismonotonic = ismonotonic(val)\n\nWrapper for ``ismonotonic``.\
\n\nParameters\n----------\n"
"val : input rank-1 array('d') with bounds (ix)\n"
"\nReturns\n-------\n"
"ismonotonic : int";
/* extern int ismonotonic(double*,int); */
static PyObject *f2py_rout__tricub_ismonotonic(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           int (*f2py_func)(double*,int)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int ismonotonic_return_value=0;
  double *val = NULL;
  npy_intp val_Dims[1] = {-1};
  const int val_Rank = 1;
  PyArrayObject *capi_val_tmp = NULL;
  int capi_val_intent = 0;
  PyObject *val_capi = Py_None;
  int ix = 0;
  static char *capi_kwlist[] = {"val",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "O:_tricub.ismonotonic",\
    capi_kwlist,&val_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable val */
  ;
  capi_val_intent |= F2PY_INTENT_C|F2PY_INTENT_IN;
  capi_val_tmp = array_from_pyobj(NPY_DOUBLE,val_Dims,val_Rank,capi_val_intent,val_capi);
  if (capi_val_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_tricub_error,"failed in converting 1st argument `val' of _tricub.ismonotonic to C/Fortran array" );
  } else {
    val = (double *)(PyArray_DATA(capi_val_tmp));

  /* Processing variable ix */
  ix = len(val);
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  ismonotonic_return_value = (*f2py_func)(val,ix);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("i",ismonotonic_return_value);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  /* End of cleaning variable ix */
  if((PyObject *)capi_val_tmp!=val_capi) {
    Py_XDECREF(capi_val_tmp); }
  }  /*if (capi_val_tmp == NULL) ... else of val*/
  /* End of cleaning variable val */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/***************************** end of ismonotonic *****************************/

/********************************* isregular *********************************/
static char doc_f2py_rout__tricub_isregular[] = "\
isregular = isregular(val)\n\nWrapper for ``isregular``.\
\n\nParameters\n----------\n"
"val : input rank-1 array('d') with bounds (ix)\n"
"\nReturns\n-------\n"
"isregular : int";
/* extern int isregular(double*,int); */
static PyObject *f2py_rout__tricub_isregular(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           int (*f2py_func)(double*,int)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int isregular_return_value=0;
  double *val = NULL;
  npy_intp val_Dims[1] = {-1};
  const int val_Rank = 1;
  PyArrayObject *capi_val_tmp = NULL;
  int capi_val_intent = 0;
  PyObject *val_capi = Py_None;
  int ix = 0;
  static char *capi_kwlist[] = {"val",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "O:_tricub.isregular",\
    capi_kwlist,&val_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable val */
  ;
  capi_val_intent |= F2PY_INTENT_C|F2PY_INTENT_IN;
  capi_val_tmp = array_from_pyobj(NPY_DOUBLE,val_Dims,val_Rank,capi_val_intent,val_capi);
  if (capi_val_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_tricub_error,"failed in converting 1st argument `val' of _tricub.isregular to C/Fortran array" );
  } else {
    val = (double *)(PyArray_DATA(capi_val_tmp));

  /* Processing variable ix */
  ix = len(val);
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  isregular_return_value = (*f2py_func)(val,ix);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("i",isregular_return_value);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  /* End of cleaning variable ix */
  if((PyObject *)capi_val_tmp!=val_capi) {
    Py_XDECREF(capi_val_tmp); }
  }  /*if (capi_val_tmp == NULL) ... else of val*/
  /* End of cleaning variable val */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/****************************** end of isregular ******************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
  {"reg_eval",-1,{{-1}},0,(char *)reg_eval,(f2py_init_func)f2py_rout__tricub_reg_eval,doc_f2py_rout__tricub_reg_eval},
  {"reg_ev",-1,{{-1}},0,(char *)reg_ev,(f2py_init_func)f2py_rout__tricub_reg_ev,doc_f2py_rout__tricub_reg_ev},
  {"nonreg_eval",-1,{{-1}},0,(char *)nonreg_eval,(f2py_init_func)f2py_rout__tricub_nonreg_eval,doc_f2py_rout__tricub_nonreg_eval},
  {"nonreg_ev",-1,{{-1}},0,(char *)nonreg_ev,(f2py_init_func)f2py_rout__tricub_nonreg_ev,doc_f2py_rout__tricub_nonreg_ev},
  {"ev",-1,{{-1}},0,(char *)ev,(f2py_init_func)f2py_rout__tricub_ev,doc_f2py_rout__tricub_ev},
  {"ismonotonic",-1,{{-1}},0,(char *)ismonotonic,(f2py_init_func)f2py_rout__tricub_ismonotonic,doc_f2py_rout__tricub_ismonotonic},
  {"isregular",-1,{{-1}},0,(char *)isregular,(f2py_init_func)f2py_rout__tricub_isregular,doc_f2py_rout__tricub_isregular},

/*eof routine_defs*/
  {NULL}
};

static PyMethodDef f2py_module_methods[] = {

  {NULL,NULL}
};

#if PY_VERSION_HEX >= 0x03000000
static struct PyModuleDef moduledef = {
  PyModuleDef_HEAD_INIT,
  "_tricub",
  NULL,
  -1,
  f2py_module_methods,
  NULL,
  NULL,
  NULL,
  NULL
};
#endif

#if PY_VERSION_HEX >= 0x03000000
#define RETVAL m
PyMODINIT_FUNC PyInit__tricub(void) {
#else
#define RETVAL
PyMODINIT_FUNC init_tricub(void) {
#endif
  int i;
  PyObject *m,*d, *s;
#if PY_VERSION_HEX >= 0x03000000
  m = _tricub_module = PyModule_Create(&moduledef);
#else
  m = _tricub_module = Py_InitModule("_tricub", f2py_module_methods);
#endif
  Py_TYPE(&PyFortran_Type) = &PyType_Type;
  import_array();
  if (PyErr_Occurred())
    {PyErr_SetString(PyExc_ImportError, "can't initialize module _tricub (failed to import numpy)"); return RETVAL;}
  d = PyModule_GetDict(m);
  s = PyString_FromString("$Revision: $");
  PyDict_SetItemString(d, "__version__", s);
#if PY_VERSION_HEX >= 0x03000000
  s = PyUnicode_FromString(
#else
  s = PyString_FromString(
#endif
    "This module '_tricub' is auto-generated with f2py (version:2).\nFunctions:\n"
"  val = reg_eval(dx0,dx1,dx2,f,pos,indx)\n"
"  val = reg_ev(x0,x1,x2,f,fx0,fx1,fx2)\n"
"  val = nonreg_eval(x0,x1,x2,f,fx0,fx1,fx2,pos,indx,in0,in1,in2)\n"
"  val = nonreg_ev(x0,x1,x2,f,fx0,fx1,fx2)\n"
"  val = ev(x0,x1,x2,f,fx0,fx1,fx2)\n"
"  ismonotonic = ismonotonic(val)\n"
"  isregular = isregular(val)\n"
".");
  PyDict_SetItemString(d, "__doc__", s);
  _tricub_error = PyErr_NewException ("_tricub.error", NULL, NULL);
  Py_DECREF(s);
  for(i=0;f2py_routine_defs[i].name!=NULL;i++)
    PyDict_SetItemString(d, f2py_routine_defs[i].name,PyFortranObject_NewAsAttr(&f2py_routine_defs[i]));







/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
  if (! PyErr_Occurred())
    on_exit(f2py_report_on_exit,(void*)"_tricub");
#endif

  return RETVAL;
}
#ifdef __cplusplus
}
#endif
